

service: ekk-support-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"
configValidationMode: off

provider:
  name: azure
  location: Canada Central
  runtime: nodejs14
  stage: ${opt:stage, 'dev'}
  resourceGroup: emojikitchenkeyboard

  apim:
    apis:
      - name: ekk-support-api
        displayName: Emoji Kitchen Keyboard Support Web API
        description: Handler for support webform
        protocols:
          - https
        path: v1
        subscriptionRequired: false
        authorization: none
  
  environment:
    FORM_COSMOS_ENDPOINT: ${param:FORM_COSMOS_ENDPOINT}
    FORM_COSMOS_KEY: ${param:FORM_COSMOS_KEY}
    FORM_DATABASE_ID: ${param:FORM_DATABASE_ID}
    FORM_CONTAINER_ID: ${param:FORM_CONTAINER_ID}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  hello:
    handler: src/handlers/hello.sayHello
    apim:
      api: ekk-support-api
      operations:
        - method: get
          urlTemplate: /hello
          displayName: Hello
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous # can also be `function` or `admin`

  goodbye:
    handler: src/handlers/goodbye.sayGoodbye
    apim:
      api: ekk-support-api
      operations:
        - method: get
          urlTemplate: /goodbye
          displayName: GoodBye
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous
  
  storeForm:
    handler: src/handlers/storeForm.storeForm
    apim:
      api: ekk-support-api
      operations:
        - method: POST
          urlTemplate: /form
          displayName: Store Form
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions
  - serverless-webpack
