name: Deploy Azure Serverless Application

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      FORM_COSMOS_ENDPOINT: ${{ secrets.FORM_COSMOS_ENDPOINT}}
      FORM_COSMOS_KEY: ${{ secrets.FORM_COSMOS_KEY}}
      FORM_DATABASE_ID: ${{ secrets.FORM_DATABASE_ID}}
      FORM_CONTAINER_ID: ${{ secrets.FORM_CONTAINER_ID}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Deploy Azure Serverless Application
      run: |
        npx serverless deploy \
          -- verbose \
          --param="FORM_COSMOS_ENDPOINT=$FORM_COSMOS_ENDPOINT" \
          --param="FORM_COSMOS_KEY=$FORM_COSMOS_KEY" \
          --param="FORM_DATABASE_ID=$FORM_DATABASE_ID" \
          --param="FORM_CONTAINER_ID=$FORM_CONTAINER_ID"
        

